### ISSUE TITLE
about the data and model

### ISSUE THREAD

**Issue by whucsu** [MatteoSalvador/cardioEM-4CH#1]
thanks for sharing.
when clone the files, the data and models can not download.
would you please share the link of ventricular pressure-volume temporal dynamics of 400 four-chamber heart electromechanical simulations ? 
best wishes.

**Comment by MatteoSalvador** [comment]
Thanks for your query @whucsu, there was an issue with the `git-lfs` quota.
I reloaded data, model and configs throughout the repo.
Everything should be available now by simply running `git clone`.
